### ISSUE TITLE
request: trait: mkdocs

### ISSUE THREAD

**Issue by eins78** [cider-ci/cider-ci_executor#3]
actually 3 traits, in order:
1. python2 (should already be present coz ansible)
2. [pip](http://pip.readthedocs.org/en/latest/installing.html)
3. [mkdocs](http://www.mkdocs.org/#installation)

**Comment by eins78** [comment]
Actually `pip` would be enough since `mkdocs` is installed with it, akin to gems and `bundler`.
On the other hand we might use it in several project, so maybe a trait is warranted.

**Comment by DrTom** [comment]
Makes sense. 

I'm not sure if pip is sufficient without further hackery. The cider-ci user `ciderex` may not write to `/usr/local`. In ruby there is the `rbenv` + `bundler` layer to access binaries and libraries. I don't know how this works with python. 

We can install mkdocs via ansible as root to `/usr/local` as we do for the ansible trait.

**Comment by eins78** [comment]
I did not think of this restriction, so a `mkdocs` trait would be the most pragmatic solution since that is what we need. 

Longterm the Python equivalent would be `virtualenv`, but that would be needed for a completely different feature: matrix tests, where you could target versions of ruby with `rbenv`, Node/iojs with `nvm` and Python with `virtualenv`.

**Comment by DrTom** [comment]
done
